package games;

import java.util.Random;

/**
 * LightsOutGame
 * --------------
 * An original implementation of the well-known, uncopyrightable
 * "click a cell to toggle it and its orthogonal neighbors, turn every
 * light off to win" grid-puzzle mechanic - a simple, purely mathematical
 * toggle puzzle (the same family as peg solitaire or Nim) with countless
 * independent implementations, no relation to any specific existing
 * game's code, grid size, or visual design. Turn-based, not real-time -
 * no tick loop, LightsOutWindow just repaints after each click.
 *
 * Puzzles are generated by starting from all-off and applying a batch of
 * random toggles - since toggling is its own inverse, this guarantees
 * the result is always solvable (a fully random on/off pattern is NOT
 * always solvable on this grid, for parity reasons, so this is the
 * standard, correct way to generate one).
 */
public class LightsOutGame
{
    public static final int SIZE = 5;

    private final boolean[][] lightOn = new boolean[SIZE][SIZE];
    private final Random random = new Random();
    private int movesUsed;
    private final int shuffleMoves;
    private boolean won;

    public LightsOutGame()
    {
        shuffleMoves = 12 + random.nextInt(8); // 12-19 random toggles to scramble from all-off
        for (int i = 0; i < shuffleMoves; i++)
        {
            toggleAround(random.nextInt(SIZE), random.nextInt(SIZE));
        }
        // An unlucky shuffle can land back on all-off (or very close to a trivial finish) - reroll toggles until there's real work to do.
        int guard = 0;
        while (isSolved() && guard < 20)
        {
            toggleAround(random.nextInt(SIZE), random.nextInt(SIZE));
            guard++;
        }
    }

    public boolean isOn(int row, int col) { return lightOn[row][col]; }
    public int getMovesUsed() { return movesUsed; }
    public boolean isWon() { return won; }

    public void click(int row, int col)
    {
        if (won) return;
        if (row < 0 || row >= SIZE || col < 0 || col >= SIZE) return;

        toggleAround(row, col);
        movesUsed++;

        if (isSolved())
        {
            won = true;
        }
    }

    private void toggleAround(int row, int col)
    {
        toggle(row, col);
        toggle(row - 1, col);
        toggle(row + 1, col);
        toggle(row, col - 1);
        toggle(row, col + 1);
    }

    private void toggle(int row, int col)
    {
        if (row < 0 || row >= SIZE || col < 0 || col >= SIZE) return;
        lightOn[row][col] = !lightOn[row][col];
    }

    private boolean isSolved()
    {
        for (int r = 0; r < SIZE; r++)
        {
            for (int c = 0; c < SIZE; c++)
            {
                if (lightOn[r][c]) return false;
            }
        }
        return true;
    }

    /** Fewer moves than the shuffle used to scramble the board is worth more - the standard "efficiency" reward shape, floored at a minimum completion bonus. */
    public int getScore()
    {
        if (!won) return 0;
        return Math.max(50, 500 - movesUsed * 10);
    }
}
