package games;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * MazeChaseGame
 * -------------
 * An original implementation of the well-known, uncopyrightable
 * "collect every pellet in a maze while avoiding roaming enemies,
 * with a temporary power-up that lets you turn the tables" mechanic.
 * No relation to any specific existing game's code, art, maze layout,
 * or character designs - the maze here is generated by a simple rule
 * (see buildMaze()), not copied from anywhere, and the four chasers
 * are plain colored dots with their own from-scratch pursuit logic.
 *
 * Grid-based, tick-driven, single-player, offline - same overall
 * shape as SnakeGame. Player and chasers move one cell per tick;
 * MazeChasePanel handles smooth interpolation between ticks and input.
 */
public class MazeChaseGame
{
    public enum Direction { UP, DOWN, LEFT, RIGHT, NONE }

    public static final int WIDTH = 19;
    public static final int HEIGHT = 15;
    public static final int STARTING_LIVES = 3;
    private static final int CHASER_COUNT = 3;
    private static final int FRIGHTENED_TICKS = 45;

    private final boolean[][] wall = new boolean[HEIGHT][WIDTH];
    private final boolean[][] pellet = new boolean[HEIGHT][WIDTH];
    private final boolean[][] powerPellet = new boolean[HEIGHT][WIDTH];
    private int pelletsRemaining;

    private int playerRow, playerCol;
    private final int playerStartRow, playerStartCol;
    private Direction playerDirection = Direction.NONE;
    private Direction pendingDirection = Direction.NONE;

    public static class Chaser
    {
        public int row, col;
        public final int startRow, startCol;
        public Direction direction = Direction.NONE;
        public boolean eatenThisFright;

        Chaser(int row, int col)
        {
            this.row = row;
            this.col = col;
            this.startRow = row;
            this.startCol = col;
        }
    }

    private final List<Chaser> chasers = new ArrayList<Chaser>();
    private final Random random = new Random();

    private int score;
    private int lives = STARTING_LIVES;
    private int frightenedTicksLeft;
    private boolean won;
    private boolean lost;

    public MazeChaseGame()
    {
        buildMaze();

        playerStartRow = HEIGHT - 2;
        playerStartCol = WIDTH / 2;
        playerRow = playerStartRow;
        playerCol = playerStartCol;

        int[] chaserCols = { WIDTH / 2 - 2, WIDTH / 2, WIDTH / 2 + 2 };
        for (int i = 0; i < CHASER_COUNT; i++)
        {
            chasers.add(new Chaser(1, chaserCols[i % chaserCols.length]));
        }

        clearAreaAroundStarts();
    }

    /** Wall pillars sit at every even row/col inside the border, everything else is open corridor - since no two pillars are ever adjacent (they're always at least 2 cells apart), removing them can never disconnect the corridor mesh, so every pellet is always reachable without needing a real maze-generation algorithm. */
    private void buildMaze()
    {
        pelletsRemaining = 0;
        for (int row = 0; row < HEIGHT; row++)
        {
            for (int col = 0; col < WIDTH; col++)
            {
                boolean isBorder = row == 0 || row == HEIGHT - 1 || col == 0 || col == WIDTH - 1;
                boolean isPillar = row % 2 == 0 && col % 2 == 0
                    && row >= 2 && row <= HEIGHT - 3 && col >= 2 && col <= WIDTH - 3;
                wall[row][col] = isBorder || isPillar;
                if (!wall[row][col])
                {
                    pellet[row][col] = true;
                    pelletsRemaining++;
                }
            }
        }

        int[][] cornerSpots = { { 1, 1 }, { 1, WIDTH - 2 }, { HEIGHT - 2, 1 }, { HEIGHT - 2, WIDTH - 2 } };
        for (int[] spot : cornerSpots)
        {
            if (pellet[spot[0]][spot[1]])
            {
                pellet[spot[0]][spot[1]] = false;
                powerPellet[spot[0]][spot[1]] = true;
            }
        }
    }

    /** The player and chaser starting cells never carry a pellet - nothing to collect just by existing where you spawn. */
    private void clearAreaAroundStarts()
    {
        pellet[playerStartRow][playerStartCol] = false;
        for (Chaser c : chasers)
        {
            if (pellet[c.startRow][c.startCol])
            {
                pellet[c.startRow][c.startCol] = false;
            }
        }
    }

    public boolean isWall(int row, int col) { return wall[row][col]; }
    public boolean hasPellet(int row, int col) { return pellet[row][col]; }
    public boolean hasPowerPellet(int row, int col) { return powerPellet[row][col]; }
    public int getPlayerRow() { return playerRow; }
    public int getPlayerCol() { return playerCol; }
    public Direction getPlayerDirection() { return playerDirection; }
    public List<Chaser> getChasers() { return chasers; }
    public int getScore() { return score; }
    public int getLives() { return lives; }
    public boolean isFrightened() { return frightenedTicksLeft > 0; }
    public boolean isWon() { return won; }
    public boolean isLost() { return lost; }
    public boolean isOver() { return won || lost; }

    public void setPendingDirection(Direction direction) { pendingDirection = direction; }

    private boolean isOpen(int row, int col)
    {
        if (row < 0 || row >= HEIGHT || col < 0 || col >= WIDTH) return false;
        return !wall[row][col];
    }

    private int[] step(int row, int col, Direction direction)
    {
        if (direction == Direction.UP)    return new int[] { row - 1, col };
        if (direction == Direction.DOWN)  return new int[] { row + 1, col };
        if (direction == Direction.LEFT)  return new int[] { row, col - 1 };
        if (direction == Direction.RIGHT) return new int[] { row, col + 1 };
        return new int[] { row, col };
    }

    private Direction opposite(Direction d)
    {
        if (d == Direction.UP) return Direction.DOWN;
        if (d == Direction.DOWN) return Direction.UP;
        if (d == Direction.LEFT) return Direction.RIGHT;
        if (d == Direction.RIGHT) return Direction.LEFT;
        return Direction.NONE;
    }

    /** Advances the game by one grid step: moves the player, moves every chaser, resolves pellet pickups and collisions. Does nothing once the game has already ended. */
    public void tick()
    {
        if (isOver()) return;

        movePlayer();
        collectAtPlayer();
        moveChasers();
        resolveCollisions();

        if (frightenedTicksLeft > 0)
        {
            frightenedTicksLeft--;
            if (frightenedTicksLeft == 0)
            {
                for (Chaser c : chasers) c.eatenThisFright = false;
            }
        }

        if (pelletsRemaining <= 0)
        {
            won = true;
        }
    }

    private void movePlayer()
    {
        if (pendingDirection != Direction.NONE)
        {
            int[] next = step(playerRow, playerCol, pendingDirection);
            if (isOpen(next[0], next[1]))
            {
                playerDirection = pendingDirection;
            }
        }
        int[] next = step(playerRow, playerCol, playerDirection);
        if (isOpen(next[0], next[1]))
        {
            playerRow = next[0];
            playerCol = next[1];
        }
    }

    private void collectAtPlayer()
    {
        if (pellet[playerRow][playerCol])
        {
            pellet[playerRow][playerCol] = false;
            pelletsRemaining--;
            score += 10;
        }
        else if (powerPellet[playerRow][playerCol])
        {
            powerPellet[playerRow][playerCol] = false;
            score += 50;
            frightenedTicksLeft = FRIGHTENED_TICKS;
            for (Chaser c : chasers) c.eatenThisFright = false;
        }
    }

    /** Each chaser picks, out of every direction that doesn't walk into a wall, the one that gets closest to the player (or furthest, while frightened) 75% of the time - and a uniformly random valid direction the rest of the time, so movement isn't perfectly predictable. Reversing straight back the way it came is avoided unless it's genuinely the only option, same as a real intersection-based chase AI. */
    private void moveChasers()
    {
        boolean fleeing = frightenedTicksLeft > 0;
        for (Chaser chaser : chasers)
        {
            List<Direction> options = new ArrayList<Direction>();
            for (Direction d : new Direction[] { Direction.UP, Direction.DOWN, Direction.LEFT, Direction.RIGHT })
            {
                int[] next = step(chaser.row, chaser.col, d);
                if (isOpen(next[0], next[1]) && d != opposite(chaser.direction))
                {
                    options.add(d);
                }
            }
            if (options.isEmpty())
            {
                for (Direction d : new Direction[] { Direction.UP, Direction.DOWN, Direction.LEFT, Direction.RIGHT })
                {
                    int[] next = step(chaser.row, chaser.col, d);
                    if (isOpen(next[0], next[1]))
                    {
                        options.add(d);
                    }
                }
            }
            if (options.isEmpty()) continue;

            Direction chosen;
            if (random.nextInt(100) < 75)
            {
                chosen = bestDirection(chaser, options, fleeing);
            }
            else
            {
                chosen = options.get(random.nextInt(options.size()));
            }

            int[] next = step(chaser.row, chaser.col, chosen);
            chaser.row = next[0];
            chaser.col = next[1];
            chaser.direction = chosen;
        }
    }

    private Direction bestDirection(Chaser chaser, List<Direction> options, boolean flee)
    {
        Direction best = options.get(0);
        int bestDist = flee ? -1 : Integer.MAX_VALUE;
        for (Direction d : options)
        {
            int[] next = step(chaser.row, chaser.col, d);
            int dist = Math.abs(next[0] - playerRow) + Math.abs(next[1] - playerCol);
            if (flee)
            {
                if (dist > bestDist) { bestDist = dist; best = d; }
            }
            else
            {
                if (dist < bestDist) { bestDist = dist; best = d; }
            }
        }
        return best;
    }

    private void resolveCollisions()
    {
        for (Chaser chaser : chasers)
        {
            if (chaser.row != playerRow || chaser.col != playerCol) continue;

            if (frightenedTicksLeft > 0 && !chaser.eatenThisFright)
            {
                chaser.eatenThisFright = true;
                chaser.row = chaser.startRow;
                chaser.col = chaser.startCol;
                chaser.direction = Direction.NONE;
                score += 200;
            }
            else if (frightenedTicksLeft <= 0)
            {
                loseLife();
                return;
            }
        }
    }

    private void loseLife()
    {
        lives--;
        if (lives <= 0)
        {
            lost = true;
            return;
        }
        playerRow = playerStartRow;
        playerCol = playerStartCol;
        playerDirection = Direction.NONE;
        pendingDirection = Direction.NONE;
        frightenedTicksLeft = 0;
        for (Chaser c : chasers)
        {
            c.row = c.startRow;
            c.col = c.startCol;
            c.direction = Direction.NONE;
            c.eatenThisFright = false;
        }
    }
}
